name: Regios
main: couk.Adamki11s.Regios.Main.Regios
version: 4.0.63
author: Adamki11s
commands:
  regios:
    aliases: [reg, r]
    description: Use /regios help <Page Number>
    usage: Regios requires the Spout server plugin!